### ISSUE TITLE
Introduce batteries for sensors

### ISSUE THREAD

**Issue by andy2great** [BesLogic/releaf-genparker#27]
Currently, we manage to read each sensor, but each sensor also have a battery attached that is used as a sensor type as well! 
In terms of releaf, each vitals has a battery and should be considered as one.

**Comment by misterbamboo** [comment]
- [x] Get Sensor#13
- [x] Create cache for each positions per device/pairingKey
- [x] Map battery level to right box vitals
- [x] Update box with new sensor data received
- [ ] Test with real data

**Comment by misterbamboo** [comment]
Sync for vitals and battery level is done.
